name: 知识文档部署📡

on:
  push:
    branches:
      - main

permissions:
  contents: write

run-name: 知识文档部署📚
jobs:
  deploy-notes:
    name: 部署流程 steps♻️
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码🔍️
        uses: actions/checkout@v4

      - name: 配置环境🔨
        run: |
          node -v
          npm i -g pnpm
          pnpm -v

      - name: 安装依赖并构建生产版本⚡️
        run: |
          pnpm -F @jiketu/docs i
          pnpm -F @jiketu/docs build

      - name: 部署🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: apps/docs/dist
