name: 预生产模式

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: 自动化发布个人博客📚
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 启动虚拟机
        run: |
          echo "测试能否联通宿主机？"
          curl -I https://www.baidu.com

      - name: 配置环境
        run: |
          node -v
          npm i -g pnpm
          pnpm -v

      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: 📦 安装依赖并运行
        run: |
          pnpm i
          pnpm docs:dev

      - name: 🚀 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          commit-message: '🚀 预生产部署'
